services:
  mysql:
    image: mysql:8.0
    container_name: soccer-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: soccerstore
      MYSQL_USER: socceruser
      MYSQL_PASSWORD: soccerpass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: soccer-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/soccerstore
      SPRING_DATASOURCE_USERNAME: socceruser
      SPRING_DATASOURCE_PASSWORD: soccerpass
    depends_on:
      - mysql

volumes:
  mysql-data: